"""
Configuration file for Legal Case Analysis System
Adjust these settings to customize system behavior.
"""

# ============================================================================
# LLM SETTINGS
# ============================================================================

# Llama model to use for LLM defense analysis
LLM_MODEL_NAME = "llama2"

# Temperature for LLM (0.0-1.0; lower = more consistent, higher = more creative)
# Legal reasoning benefits from lower temperature (0.3 = conservative)
LLM_TEMPERATURE = 0.3

# Backend for LLM ("ollama", "huggingface", "local")
# "ollama" requires ollama running locally
LLM_BACKEND = "ollama"

# Enable LLM defense analysis by default
LLM_ENABLED = True

# Default weight for LLM in scoring (0.0-1.0)
# 0.7 = 70% LLM weight, 30% symbolic weight
LLM_WEIGHT_DEFAULT = 0.7

# ============================================================================
# TTS (TEXT-TO-SPEECH) SETTINGS
# ============================================================================

# TTS backend ("coqui", "pyttsx3", "auto")
# "coqui" = best quality, offline, ~500MB model
# "pyttsx3" = fast, robotic, always available
# "auto" = try coqui, fallback to pyttsx3
TTS_BACKEND = "coqui"

# Enable TTS by default
TTS_ENABLED = False

# TTS speech rate (words per minute)
# 120-140 recommended for legal clarity
TTS_RATE_WPM = 120

# ============================================================================
# BURDEN OF PROOF SETTINGS
# ============================================================================

# Default threshold for guilt verdict
# 0.6 = prosecution needs 60% advantage to secure guilty verdict
# 0.4 = easier threshold for guilty, more conservative
# 0.8 = harder threshold for guilty, more lenient to accused
THETA_DEFAULT = 0.6

# Threshold range boundaries for UI
THETA_MIN = 0.3
THETA_MAX = 0.9

# ============================================================================
# WEB INTERFACE SETTINGS
# ============================================================================

# Flask debug mode
FLASK_DEBUG = False

# Maximum case file upload size (in bytes)
# 10MB default
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# Default port for web server
WEB_PORT = 5000

# Enable profiling for performance analysis
ENABLE_PROFILING = False

# ============================================================================
# DATABASE / STORAGE SETTINGS
# ============================================================================

# Directory for storing uploaded files
UPLOAD_FOLDER = "uploads"

# Directory for storing generated reports
REPORTS_FOLDER = "reports"

# Directory for storing audio files
AUDIO_FOLDER = "audio"

# Temporary directory for processing
TEMP_FOLDER = "temp"

# ============================================================================
# SYSTEM BEHAVIOR SETTINGS
# ============================================================================

# Maximum number of charges to evaluate per case
MAX_CHARGES = 10

# Minimum confidence threshold to display verdict (0.0-1.0)
MIN_CONFIDENCE_DISPLAY = 0.0

# Enable verbose logging
VERBOSE = False

# Enable debug mode (prints all reasoning steps)
DEBUG = False

# ============================================================================
# CASE ANALYSIS DEFAULTS
# ============================================================================

# Supported charges (expandable)
SUPPORTED_CHARGES = [
    "Assault on Minor",
    "Assault",
    "Aggravated Assault",
    "Battery",
    "Theft",
    "Robbery",
    "Fraud",
    "Murder"
]

# Default charges if none specified
DEFAULT_CHARGES = ["Assault on Minor"]

# ============================================================================
# DEFENSE ANALYSIS SETTINGS
# ============================================================================

# Defense argument scoring weights
DEFENSE_STRENGTH_WEIGHT = 0.4        # Weight for stated strength
DEFENSE_GROUNDING_WEIGHT = 0.3       # Weight for fact grounding
DEFENSE_CONFIDENCE_WEIGHT = 0.3      # Weight for supporting fact confidence

# Minimum grounding factor required for valid argument
MIN_GROUNDING_FACTOR = 0.3

# ============================================================================
# METADATA / SYSTEM INFO
# ============================================================================

# System version
SYSTEM_VERSION = "2.0.0"

# System name
SYSTEM_NAME = "Neuro-Symbolic Legal Analysis System with LLM Defense"

# Author info for reports
REPORT_AUTHOR = "AI Legal Analysis System"

# Disclaimer for all reports
LEGAL_DISCLAIMER = """
DISCLAIMER: This analysis is generated by an artificial intelligence system
combining neuro-symbolic reasoning with large language models. It is intended
for educational and informational purposes only. It is NOT a substitute for
qualified legal counsel. Actual legal proceedings require representation by
licensed attorneys and proper court adjudication in lawful jurisdiction.
This system's conclusions should not be relied upon for binding legal decisions.
"""
